// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfdeduLNV8KtmaO5NxMwOCwkYuUV30U4M',
    appId: '1:844679899822:web:b38a22f785abb38d161b3f',
    messagingSenderId: '844679899822',
    projectId: 'readarc-dcf31',
    authDomain: 'readarc-dcf31.firebaseapp.com',
    storageBucket: 'readarc-dcf31.appspot.com',
    measurementId: 'G-56QB4JN9GB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHajAuTISBxtmFMveZ_4rnFc-IAXg-Gb4',
    appId: '1:844679899822:android:ad42deaff86fcb26161b3f',
    messagingSenderId: '844679899822',
    projectId: 'readarc-dcf31',
    storageBucket: 'readarc-dcf31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyM3Qf4ginj9V_Rv21CGBryamURpTqxeU',
    appId: '1:844679899822:ios:01454dbe50af69fd161b3f',
    messagingSenderId: '844679899822',
    projectId: 'readarc-dcf31',
    storageBucket: 'readarc-dcf31.appspot.com',
    iosBundleId: 'com.example.readarc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyM3Qf4ginj9V_Rv21CGBryamURpTqxeU',
    appId: '1:844679899822:ios:01454dbe50af69fd161b3f',
    messagingSenderId: '844679899822',
    projectId: 'readarc-dcf31',
    storageBucket: 'readarc-dcf31.appspot.com',
    iosBundleId: 'com.example.readarc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfdeduLNV8KtmaO5NxMwOCwkYuUV30U4M',
    appId: '1:844679899822:web:97a39db7cf7254b0161b3f',
    messagingSenderId: '844679899822',
    projectId: 'readarc-dcf31',
    authDomain: 'readarc-dcf31.firebaseapp.com',
    storageBucket: 'readarc-dcf31.appspot.com',
    measurementId: 'G-GJ2NPETEJ6',
  );
}
